# prod overrides - image tag/digest updated by ci's prod-promotion pr (step 8.6),
# starting from whatever's currently proven working in dev
image:
  repository: "262786914511.dkr.ecr.us-east-1.amazonaws.com/realworld-backend"
  tag: "09b4fb3"
  digest: "sha256:a83d1ffa0b19f58964eeda2543104074290015acf85cd013f59c4bae53a59113"

replicaCount: 1

ingress:
  groupOrder: "30"
  listenPort: 8080
