# prod overrides - image tag/digest updated by ci's prod-promotion pr (step 8.6),
# starting from whatever's currently proven working in dev
image:
  repository: "262786914511.dkr.ecr.us-east-1.amazonaws.com/realworld-backend"
  tag: "779708c"
  digest: "sha256:66ed376636e9e0cbc2fb646692318a2b4b8c2a19a381820ea0fa8825fc37e9aa"

replicaCount: 1

ingress:
  groupOrder: "30"
  listenPort: 8080
