# prod overrides - image tag/digest updated by ci's prod-promotion pr (step 8.6),
# starting from whatever's currently proven working in dev
image:
  repository: "262786914511.dkr.ecr.us-east-1.amazonaws.com/realworld-backend"
  tag: "42205c6"
  digest: "sha256:1d602bdee6a39ff738cece74369c50856920b6f3482a3d6c8b8df6c6e291ffbc"

replicaCount: 1

ingress:
  groupOrder: "30"
  listenPort: 8080
