# prod overrides - image tag/digest updated by ci's prod-promotion pr (step 8.6),
# starting from whatever's currently proven working in dev
image:
  repository: "262786914511.dkr.ecr.us-east-1.amazonaws.com/realworld-frontend"
  tag: "ec5e2ca"
  digest: "sha256:3977d0f2e90da800757073bd236ea0410ec8490aaad54ccf6b153c7f9ab7e56f"

replicaCount: 1

ingress:
  groupOrder: "40"
  listenPort: 8080
