# dev overrides - image tag/digest updated automatically by ci on every push (step 8.5)
image:
  repository: "262786914511.dkr.ecr.us-east-1.amazonaws.com/realworld-backend"
  tag: "09b4fb3"
  digest: "sha256:a83d1ffa0b19f58964eeda2543104074290015acf85cd013f59c4bae53a59113"

replicaCount: 2
